url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Abbavaram Gowtham Reddy" # the name of your site, e.g. ACME Corp.
description: "Postdoctoral Researcher at the CISPA Helmholtz Center for Information Security"
