menu:
# - {name: 'people', url: '/people'}
- {name: 'Publications', url: '/publications'}
# - {name: 'courses', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'ai ai-google-scholar', link: 'https://scholar.google.com/citations?user=Iewg-GAAAAAJ&hl=en'}
- {icon: 'fab fa-github', link: 'https://github.com/gautam0707'}
- {icon: 'fab fa-twitter', link: 'https://twitter.com/abbavaram_reddy'}
- {icon: 'fab fa-linkedin', link: 'https://linkedin.com/in/gowthamabbavaram'}

contacts:
- {name: 'Abbavaram Gowtham Reddy', department: 'CISPA Helmholtz Center for Information Security', institution_address: 'Saarbrücken', phone: '+49 155 1055 2140', email: 'gowtham.abbavaram@cispa.de'}
